baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Abstract struct'
theme ="hugo-theme-stack"
featuredImageField = "cover_image"
[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"
[caches]
    [caches.images]
        dir = ':cacheDir/images'