baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"
[caches]
    [caches.images]
        dir = ':cacheDir/images'