baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Abstract struct'
theme ="hugo-theme-stack"
[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"
[caches]
    [caches.images]
        dir = ':cacheDir/images'
[params]
  mainSections = ["posts"]

  [params.sidebar]
    emoji = ""
    subtitle = "Welcome to my blog"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "images/profile.jpg"


[menu]
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
    identifier = "home"
    [menu.main.params]
        icon = "home"
        newTab = false

